replicaCount: 1

backend:
  image:
    repository: gitops-demo-backend
    tag: "latest"
    pullPolicy: Never        # Never pull — image loaded directly into Minikube
  port: 8000
  resources:
    limits:
      cpu: 200m
      memory: 256Mi

frontend:
  image:
    repository: gitops-demo-frontend
    tag: "latest"
    pullPolicy: Never        # Never pull — image loaded directly into Minikube
  port: 80
  resources:
    limits:
      cpu: 100m
      memory: 128Mi

ingress:
  enabled: true
  host: gitops-demo.local

namespace: gitops-demo